---
- hosts: all
  vars:
       hosts: "{{ inventory_hostname }}"

  tasks:
  
      - name: Deadsnakes PPA to get Python 3.6
        apt_repository:
           repo='ppa:fkrull/deadsnakes'
      - name: make sure required packages are installed
        apt: pkg=nginx,git,python3,python3-venv state=present

      - name: allow long hostnames in nginx
        lineinfile:
           dest=/etc/nginx/nginx.conf
           regexp='(\s+)#? ?server_names_hash_bucket_size'
           backrefs=yes
           line='\1server_names_hash_bucket_size 64;'

      - name: add nginx config to sites-available
        template: src=./nginx.conf.j2 dest=/etc/nginx/sites-available/{{ host }}
        notify:
            - restart nginx

      - name: add symlink in nginx sites-enabled
        file:
            src=/etc/nginx/sites-available/{{ host }}
            dest=/etc/nginx/sites-enabled/{{ host }}
            state=link
        notify:
            - restart nginx

      - name: git source
        shell:
            mkdir -p ~/sites/{{ host }}
        shell:
            rm -rf ~/sites/{{ host }}/source
        shell:
            git clone https://github.com/yanzhen74/book-example.git ~/sites/{{ host }}/source/ 

      - name: write gunicorn service script
        template:
            src=./gunicorn.service.j2
            dest=/etc/systemd/system/gunicorn-{{ host }}.service
        notify:
            - restart gunicorn

      - name: write gunicorn supervisor script
        template:
            src=./gunicorn-supervisor.conf.j2
            dest=/home/oliver/sites/gunicorn-supervisor-{{ host }}.conf
        notify:
            - restart gunicorn

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart gunicorn
      shell:
          name=gunicorn-{{ host }}

